<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Tenant;
use App\Models\User;
use App\Models\VirtualDevice;
use App\Support\TenantContext;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;

class AuthController extends Controller
{
    /**
     * Login and obtain a Sanctum token.
     *
     * Accepts: email, password, device_name (unique name for this device),
     *          device_uuid (stable UUID generated by the mobile app), tenant_slug (optional).
     *
     * Returns: token, user, tenant, permissions, location.
     */
    public function login(Request $request): JsonResponse
    {
        $data = $request->validate([
            'email'       => ['required', 'email'],
            'password'    => ['required', 'string'],
            'device_name' => ['required', 'string', 'max:100'],
            'device_uuid' => ['nullable', 'string', 'max:64'],
            'tenant_slug' => ['nullable', 'string'],
        ]);

        $user = User::where('email', $data['email'])->first();

        if (! $user || ! Hash::check($data['password'], $user->password)) {
            throw ValidationException::withMessages([
                'email' => ['Identifiants incorrects.'],
            ]);
        }

        if (! $user->is_active) {
            return response()->json(['ok' => false, 'message' => 'Compte désactivé.'], 403);
        }

        // Resolve tenant.
        $tenantSlug = $data['tenant_slug'] ?? null;
        $tenant = $tenantSlug
            ? Tenant::where('slug', $tenantSlug)->first()
            : TenantContext::resolve($request, $user);

        if (! $tenant || ! $user->tenants()->whereKey($tenant->id)->exists()) {
            return response()->json(['ok' => false, 'message' => 'Accès tenant refusé.'], 403);
        }

        // Ensure or create a VirtualDevice for this mobile device.
        $device     = null;
        $deviceUuid = $data['device_uuid'] ?? null;
        if ($deviceUuid) {
            $device = VirtualDevice::firstOrCreate(
                ['tenant_id' => $tenant->id, 'code' => $deviceUuid],
                [
                    'name'      => $data['device_name'],
                    'type'      => 'mobile',
                    'is_active' => true,
                ]
            );
        }

        // Revoke any previous token for this device_name to avoid token accumulation.
        $user->tokens()->where('name', $data['device_name'])->delete();

        $abilities = $this->abilitiesForUser($tenant, $user);

        $token = $user->createToken($data['device_name'], $abilities);

        // Remember tenant for future requests from this token.
        $user->update(['current_tenant_id' => $tenant->id]);

        $location = \App\Models\Location::where('tenant_id', $tenant->id)
            ->where('is_default', true)
            ->first()
            ?? \App\Models\Location::where('tenant_id', $tenant->id)->first();

        return response()->json([
            'ok'    => true,
            'token' => $token->plainTextToken,
            'user'  => [
                'id'    => $user->id,
                'name'  => $user->name,
                'email' => $user->email,
            ],
            'tenant' => [
                'id'       => $tenant->id,
                'name'     => $tenant->name,
                'slug'     => $tenant->slug,
                'currency' => $tenant->currency ?? 'MAD',
                'locale'   => $tenant->locale ?? 'fr',
                'timezone' => $tenant->timezone ?? 'Africa/Casablanca',
            ],
            'location'   => $location ? ['id' => $location->id, 'name' => $location->name] : null,
            'device_id'  => $device?->id,
            'abilities'  => $abilities,
        ]);
    }

    /** Revoke the current token. */
    public function logout(Request $request): JsonResponse
    {
        $token = $request->user()->currentAccessToken();

        // TransientToken (actingAs in tests) has no delete(). Guard gracefully.
        if (method_exists($token, 'delete')) {
            $token->delete();
        }

        return response()->json(['ok' => true]);
    }

    /** Return the authenticated user + tenant context. */
    public function me(Request $request): JsonResponse
    {
        $user   = $request->user();
        $tenant = $request->attributes->get('api_tenant');
        $location = $request->attributes->get('api_location');

        $tenantUser = $tenant->users()->whereKey($user->id)->first();
        $role = $tenantUser?->pivot?->role;

        return response()->json([
            'ok'   => true,
            'user' => [
                'id'    => $user->id,
                'name'  => $user->name,
                'email' => $user->email,
                'role'  => $role,
            ],
            'tenant' => [
                'id'       => $tenant->id,
                'name'     => $tenant->name,
                'slug'     => $tenant->slug,
                'currency' => $tenant->currency ?? 'MAD',
                'locale'   => $tenant->locale ?? 'fr',
                'timezone' => $tenant->timezone ?? 'Africa/Casablanca',
            ],
            'location'   => $location ? ['id' => $location->id, 'name' => $location->name] : null,
            'abilities'  => $this->abilitiesForUser($tenant, $user),
        ]);
    }

    private function abilitiesForUser(Tenant $tenant, User $user): array
    {
        $tenantUser = $tenant->users()->whereKey($user->id)->first();
        $permissions = json_decode((string) ($tenantUser?->pivot?->permissions ?? '[]'), true) ?: [];

        if (in_array('*', $permissions, true)) {
            return ['*'];
        }

        return $permissions ?: ['pos.sales.create', 'pos.sales.view', 'catalog.view', 'stock.view'];
    }
}
