<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Tenant;
use App\Models\User;
use App\Models\VirtualDevice;
use App\Support\TenantContext;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use OpenApi\Attributes as OA;

class AuthController extends Controller
{
    /**
     * Login and obtain a Sanctum token.
     *
     * Accepts: email, password, device_name (unique name for this device),
     *          device_uuid (stable UUID generated by the mobile app), tenant_slug (optional).
     *
     * Returns: token, user, tenant, permissions, location.
     */
    #[OA\Post(
        path: '/api/v1/auth/login',
        operationId: 'authLogin',
        summary: 'Login and get API token',
        description: 'Authenticates a user and returns a Sanctum token along with tenant and location context.',
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(
                required: ['email', 'password', 'device_name'],
                properties: [
                    new OA\Property(property: 'email', type: 'string', format: 'email', example: 'cashier@example.com'),
                    new OA\Property(property: 'password', type: 'string', format: 'password', example: 'secret'),
                    new OA\Property(property: 'device_name', type: 'string', example: 'iPad-POS-01'),
                    new OA\Property(property: 'tenant_slug', type: 'string', nullable: true, example: 'my-store'),
                    new OA\Property(property: 'device_uuid', type: 'string', nullable: true, example: '550e8400-e29b-41d4-a716-446655440000'),
                ],
            )
        ),
        tags: ['Auth'],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Login successful',
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: 'ok', type: 'boolean', example: true),
                        new OA\Property(property: 'token', type: 'string', example: '1|abc123...'),
                        new OA\Property(property: 'user', type: 'object', properties: [
                            new OA\Property(property: 'id', type: 'integer'),
                            new OA\Property(property: 'name', type: 'string'),
                            new OA\Property(property: 'email', type: 'string'),
                        ]),
                        new OA\Property(property: 'tenant', type: 'object', properties: [
                            new OA\Property(property: 'id', type: 'integer'),
                            new OA\Property(property: 'name', type: 'string'),
                            new OA\Property(property: 'slug', type: 'string'),
                            new OA\Property(property: 'currency', type: 'string'),
                            new OA\Property(property: 'locale', type: 'string'),
                            new OA\Property(property: 'timezone', type: 'string'),
                        ]),
                        new OA\Property(property: 'location', type: 'object', nullable: true, properties: [
                            new OA\Property(property: 'id', type: 'integer'),
                            new OA\Property(property: 'name', type: 'string'),
                        ]),
                        new OA\Property(property: 'abilities', type: 'array', items: new OA\Items(type: 'string')),
                    ]
                )
            ),
            new OA\Response(response: 422, description: 'Validation error or invalid credentials'),
            new OA\Response(response: 403, description: 'Account disabled or tenant access denied'),
        ]
    )]
    public function login(Request $request): JsonResponse
    {
        $data = $request->validate([
            'email'       => ['required', 'email'],
            'password'    => ['required', 'string'],
            'device_name' => ['required', 'string', 'max:100'],
            'device_uuid' => ['nullable', 'string', 'max:64'],
            'tenant_slug' => ['nullable', 'string'],
        ]);

        $user = User::where('email', $data['email'])->first();

        if (! $user || ! Hash::check($data['password'], $user->password)) {
            throw ValidationException::withMessages([
                'email' => ['Identifiants incorrects.'],
            ]);
        }

        if (! $user->is_active) {
            return response()->json(['ok' => false, 'message' => 'Compte désactivé.'], 403);
        }

        // Resolve tenant.
        $tenantSlug = $data['tenant_slug'] ?? null;
        $tenant = $tenantSlug
            ? Tenant::where('slug', $tenantSlug)->first()
            : TenantContext::resolve($request, $user);

        if (! $tenant || ! $user->tenants()->whereKey($tenant->id)->exists()) {
            return response()->json(['ok' => false, 'message' => 'Accès tenant refusé.'], 403);
        }

        // Ensure or create a VirtualDevice for this mobile device.
        $device     = null;
        $deviceUuid = $data['device_uuid'] ?? null;
        if ($deviceUuid) {
            $device = VirtualDevice::firstOrCreate(
                ['tenant_id' => $tenant->id, 'code' => $deviceUuid],
                [
                    'name'      => $data['device_name'],
                    'type'      => 'mobile',
                    'is_active' => true,
                ]
            );
        }

        // Revoke any previous token for this device_name to avoid token accumulation.
        $user->tokens()->where('name', $data['device_name'])->delete();

        [$role, $abilities] = $this->resolveUserContext($tenant, $user);

        $token = $user->createToken($data['device_name'], $abilities);

        // Remember tenant for future requests from this token.
        $user->update(['current_tenant_id' => $tenant->id]);

        $location = \App\Models\Location::where('tenant_id', $tenant->id)
            ->where('is_default', true)
            ->first()
            ?? \App\Models\Location::where('tenant_id', $tenant->id)->first();

        return response()->json([
            'ok'    => true,
            'token' => $token->plainTextToken,
            'user'  => [
                'id'           => $user->id,
                'name'         => $user->name,
                'email'        => $user->email,
                'role'         => $role,
                'avatar_color' => $user->avatar_color ?? '#0D9488',
            ],
            'tenant' => [
                'id'       => $tenant->id,
                'name'     => $tenant->name,
                'slug'     => $tenant->slug,
                'currency' => $tenant->currency ?? 'MAD',
                'locale'   => $tenant->locale ?? 'fr',
                'timezone' => $tenant->timezone ?? 'Africa/Casablanca',
            ],
            'location'   => $location ? ['id' => $location->id, 'name' => $location->name] : null,
            'device_id'  => $device?->id,
            'abilities'  => $abilities,
        ]);
    }

    /** Revoke the current token. */
    #[OA\Post(
        path: '/api/v1/auth/logout',
        operationId: 'authLogout',
        summary: 'Logout and revoke token',
        security: [['bearerAuth' => []]],
        tags: ['Auth'],
        parameters: [
            new OA\Parameter(name: 'X-Tenant-Slug', in: 'header', required: true, schema: new OA\Schema(type: 'string')),
            new OA\Parameter(name: 'X-Location-Id', in: 'header', required: true, schema: new OA\Schema(type: 'integer')),
        ],
        responses: [
            new OA\Response(response: 200, description: 'Token revoked', content: new OA\JsonContent(
                properties: [new OA\Property(property: 'ok', type: 'boolean', example: true)]
            )),
            new OA\Response(response: 401, description: 'Unauthenticated'),
        ]
    )]
    public function logout(Request $request): JsonResponse
    {
        $token = $request->user()->currentAccessToken();

        // TransientToken (actingAs in tests) has no delete(). Guard gracefully.
        if (method_exists($token, 'delete')) {
            $token->delete();
        }

        return response()->json(['ok' => true]);
    }

    /** Return the authenticated user + tenant context. */
    #[OA\Get(
        path: '/api/v1/auth/me',
        operationId: 'authMe',
        summary: 'Get current authenticated user',
        security: [['bearerAuth' => []]],
        tags: ['Auth'],
        parameters: [
            new OA\Parameter(name: 'X-Tenant-Slug', in: 'header', required: true, schema: new OA\Schema(type: 'string')),
            new OA\Parameter(name: 'X-Location-Id', in: 'header', required: true, schema: new OA\Schema(type: 'integer')),
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Current user info',
                content: new OA\JsonContent(properties: [
                    new OA\Property(property: 'ok', type: 'boolean', example: true),
                    new OA\Property(property: 'user', type: 'object', properties: [
                        new OA\Property(property: 'id', type: 'integer'),
                        new OA\Property(property: 'name', type: 'string'),
                        new OA\Property(property: 'email', type: 'string'),
                        new OA\Property(property: 'role', type: 'string', nullable: true),
                    ]),
                    new OA\Property(property: 'tenant', type: 'object', properties: [
                        new OA\Property(property: 'id', type: 'integer'),
                        new OA\Property(property: 'name', type: 'string'),
                        new OA\Property(property: 'slug', type: 'string'),
                        new OA\Property(property: 'currency', type: 'string'),
                        new OA\Property(property: 'locale', type: 'string'),
                        new OA\Property(property: 'timezone', type: 'string'),
                    ]),
                    new OA\Property(property: 'location', type: 'object', nullable: true, properties: [
                        new OA\Property(property: 'id', type: 'integer'),
                        new OA\Property(property: 'name', type: 'string'),
                    ]),
                    new OA\Property(property: 'abilities', type: 'array', items: new OA\Items(type: 'string')),
                ])
            ),
            new OA\Response(response: 401, description: 'Unauthenticated'),
        ]
    )]
    public function me(Request $request): JsonResponse
    {
        $user   = $request->user();
        $tenant = $request->attributes->get('api_tenant');
        $location = $request->attributes->get('api_location');

        [$role, $meAbilities] = $this->resolveUserContext($tenant, $user);

        return response()->json([
            'ok'   => true,
            'user' => [
                'id'           => $user->id,
                'name'         => $user->name,
                'email'        => $user->email,
                'role'         => $role,
                'avatar_color' => $user->avatar_color ?? '#0D9488',
            ],
            'tenant' => [
                'id'       => $tenant->id,
                'name'     => $tenant->name,
                'slug'     => $tenant->slug,
                'currency' => $tenant->currency ?? 'MAD',
                'locale'   => $tenant->locale ?? 'fr',
                'timezone' => $tenant->timezone ?? 'Africa/Casablanca',
            ],
            'location'   => $location ? ['id' => $location->id, 'name' => $location->name] : null,
            'abilities'  => $meAbilities,
        ]);
    }

    /**
     * Returns [role, abilities] for a user in a given tenant — single DB query.
     */
    private function resolveUserContext(Tenant $tenant, User $user): array
    {
        $tenantUser = $tenant->users()->whereKey($user->id)->first();
        $roleKey    = $tenantUser?->pivot?->role;

        $role = $roleKey
            ? $tenant->roles()->where('key', $roleKey)->first()
            : null;

        $permissions = $role?->permissions ?? [];

        if (in_array('*', $permissions, true)) {
            return [$roleKey, ['*']];
        }

        $abilities = ! empty($permissions)
            ? $permissions
            : ['sales.view', 'items.view', 'stock.view'];

        return [$roleKey, $abilities];
    }
}
