<?php

use App\Http\Controllers\LibraireProController;
use Illuminate\Support\Facades\Route;

Route::get('/', [LibraireProController::class, 'dashboard'])->name('dashboard');

Route::redirect('/items', '/catalogue?panel=articles')->name('legacy.items');
Route::redirect('/items/add', '/catalogue?panel=ajouter')->name('legacy.items.add');
Route::redirect('/services/add', '/catalogue?panel=ajouter-service')->name('legacy.services.add');
Route::redirect('/category/view', '/catalogue?panel=categories')->name('legacy.categories.view');
Route::redirect('/brands/view', '/catalogue?panel=marques')->name('legacy.brands.view');
Route::redirect('/variants/view', '/catalogue?panel=variantes')->name('legacy.variants.view');
Route::redirect('/items/labels', '/catalogue/etiquettes')->name('legacy.items.labels');
Route::redirect('/import/items', '/catalogue?panel=import&kind=items')->name('legacy.import.items');
Route::redirect('/import/services', '/catalogue?panel=import&kind=services')->name('legacy.import.services');
Route::redirect('/pos', '/caisse')->name('legacy.pos');
Route::redirect('/sales/add', '/modules/sales?section=add')->name('legacy.sales.add');
Route::redirect('/sales', '/modules/sales?section=list')->name('legacy.sales');
Route::redirect('/sales_payments', '/modules/sales?section=payments')->name('legacy.sales.payments');
Route::redirect('/sales_payments/', '/modules/sales?section=payments');
Route::redirect('/sales_return', '/modules/sales?section=returns')->name('legacy.sales.returns');
Route::redirect('/delivery', '/modules/sales?section=delivery')->name('legacy.delivery');
Route::redirect('/invoice', '/modules/sales?section=invoices')->name('legacy.invoice');
Route::redirect('/purchase/add', '/modules/purchases?section=add')->name('legacy.purchase.add');
Route::redirect('/purchase', '/modules/purchases?section=list')->name('legacy.purchase');
Route::redirect('/purchase_return', '/modules/purchases?section=returns')->name('legacy.purchase.returns');
Route::redirect('/expense', '/modules/finance?section=expenses')->name('legacy.expense');
Route::redirect('/expense/add', '/modules/finance?section=expense-add')->name('legacy.expense.add');
Route::redirect('/expense/category', '/modules/finance?section=expense-categories')->name('legacy.expense.categories');
Route::redirect('/quotation/add', '/modules/sales?section=quote-add')->name('legacy.quotation.add');
Route::redirect('/quotation', '/modules/sales?section=quotes')->name('legacy.quotation');
Route::redirect('/customers/add', '/modules/contacts?section=customer-add')->name('legacy.customers.add');
Route::redirect('/customers', '/modules/contacts?section=customers')->name('legacy.customers');
Route::redirect('/import/customers', '/modules/contacts?section=import-customers')->name('legacy.import.customers');
Route::redirect('/suppliers/add', '/modules/contacts?section=supplier-add')->name('legacy.suppliers.add');
Route::redirect('/suppliers', '/modules/contacts?section=suppliers')->name('legacy.suppliers');
Route::redirect('/import/suppliers', '/modules/contacts?section=import-suppliers')->name('legacy.import.suppliers');
Route::redirect('/customers_advance/add', '/modules/finance?section=advance-add')->name('legacy.advance.add');
Route::redirect('/customers_advance', '/modules/finance?section=advances')->name('legacy.advance');
Route::redirect('/customer_coupon/generate', '/modules/finance?section=customer-coupon-add')->name('legacy.customer_coupon.add');
Route::redirect('/customer_coupon', '/modules/finance?section=customer-coupons')->name('legacy.customer_coupon');
Route::redirect('/discount_coupon/add', '/modules/finance?section=coupon-add')->name('legacy.discount_coupon.add');
Route::redirect('/discount_coupon/view', '/modules/finance?section=coupons')->name('legacy.discount_coupon');
Route::redirect('/accounts/add', '/modules/finance?section=account-add')->name('legacy.accounts.add');
Route::redirect('/accounts', '/modules/finance?section=accounts')->name('legacy.accounts');
Route::redirect('/money_transfer', '/modules/finance?section=transfers')->name('legacy.money_transfer');
Route::redirect('/money_deposit', '/modules/finance?section=deposits')->name('legacy.money_deposit');
Route::redirect('/accounts/cash_transactions', '/modules/finance?section=cash')->name('legacy.cash_transactions');
Route::redirect('/stock_adjustment', '/catalogue?panel=articles&stock=low')->name('legacy.stock_adjustment');
Route::redirect('/stock_transfer/view', '/catalogue?panel=articles&section=stock-transfer')->name('legacy.stock_transfer');
Route::redirect('/users/view', '/modules/settings?section=users')->name('legacy.users');
Route::redirect('/roles/view', '/modules/settings?section=roles')->name('legacy.roles');
Route::redirect('/sms', '/modules/settings?section=messaging')->name('legacy.sms');
Route::redirect('/templates/sms', '/modules/settings?section=message-templates')->name('legacy.sms.templates');
Route::redirect('/reports/profit_loss', '/modules/reports?section=profit-loss')->name('legacy.report.profit_loss');
Route::redirect('/reports/sales_and_payments', '/modules/reports?section=sales-payments')->name('legacy.report.sales_payments');
Route::redirect('/reports/customer_orders', '/modules/reports?section=customer-orders')->name('legacy.report.customer_orders');
Route::redirect('/reports/sales', '/modules/reports?section=sales')->name('legacy.report.sales');
Route::redirect('/reports/purchase', '/modules/reports?section=purchases')->name('legacy.report.purchase');
Route::redirect('/reports/expense', '/modules/reports?section=expenses')->name('legacy.report.expense');
Route::redirect('/reports/stock', '/modules/reports?section=stock')->name('legacy.report.stock');
Route::redirect('/warehouse', '/modules/settings?section=warehouses')->name('legacy.warehouse');
Route::redirect('/store_profile/update/2', '/modules/settings?section=company')->name('legacy.store_profile');
Route::redirect('/sms/api', '/modules/settings?section=sms-api')->name('legacy.sms_api');
Route::redirect('/tax', '/modules/settings?section=taxes')->name('legacy.tax');
Route::redirect('/units', '/modules/settings?section=units')->name('legacy.units');
Route::redirect('/units/', '/modules/settings?section=units');
Route::redirect('/payment_types', '/modules/settings?section=payment-types')->name('legacy.payment_types');
Route::redirect('/payment_types/', '/modules/settings?section=payment-types');
Route::redirect('/country', '/modules/settings?section=countries')->name('legacy.country');
Route::redirect('/state', '/modules/settings?section=states')->name('legacy.state');
Route::redirect('/users/password_reset', '/modules/settings?section=password')->name('legacy.password');

Route::get('/catalogue', [LibraireProController::class, 'catalog'])->name('catalog');
Route::get('/catalogue/data', [LibraireProController::class, 'catalogData'])->name('catalog.data');
Route::post('/catalogue/articles', [LibraireProController::class, 'storeItem'])->name('catalog.items.store');
Route::put('/catalogue/articles/{item}', [LibraireProController::class, 'updateItem'])->name('catalog.items.update');
Route::delete('/catalogue/articles/{item}', [LibraireProController::class, 'destroyItem'])->name('catalog.items.destroy');
Route::post('/catalogue/categories', [LibraireProController::class, 'storeCategory'])->name('catalog.categories.store');
Route::post('/catalogue/marques', [LibraireProController::class, 'storeBrand'])->name('catalog.brands.store');
Route::post('/catalogue/unites', [LibraireProController::class, 'storeUnit'])->name('catalog.units.store');
Route::post('/catalogue/taxes', [LibraireProController::class, 'storeTax'])->name('catalog.taxes.store');
Route::post('/catalogue/variantes', [LibraireProController::class, 'storeVariant'])->name('catalog.variants.store');
Route::post('/catalogue/import', [LibraireProController::class, 'importItems'])->name('catalog.import');
Route::get('/catalogue/export', [LibraireProController::class, 'exportCatalog'])->name('catalog.export');
Route::get('/catalogue/etiquettes', [LibraireProController::class, 'labels'])->name('catalog.labels');
Route::get('/caisse', [LibraireProController::class, 'pos'])->name('pos');
Route::post('/parametres/theme', [LibraireProController::class, 'updateTheme'])->name('settings.theme.update');
Route::get('/modules/{module}', [LibraireProController::class, 'module'])->name('module');
