<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommercialDocumentController;
use App\Http\Controllers\LibraireProController;
use App\Http\Controllers\OnlineStoreController;
use App\Http\Controllers\VariantController;
use App\Http\Controllers\VirtualDeviceController;
use Illuminate\Support\Facades\Route;

Route::get('/manifest.json', [LibraireProController::class, 'manifest'])->name('manifest');
Route::get('/app-icon/{size}', [LibraireProController::class, 'appIcon'])->where('size', '32|192|512')->name('app.icon');
Route::get('/connexion', [AuthController::class, 'showLogin'])->name('login');
Route::post('/connexion', [AuthController::class, 'login'])->name('login.store');
Route::post('/deconnexion', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::get('/profil', [AuthController::class, 'profile'])->middleware(['auth', 'session.unlocked'])->name('profile');
Route::put('/profil', [AuthController::class, 'updateProfile'])->middleware(['auth', 'session.unlocked'])->name('profile.update');
Route::get('/profil/activite', [AuthController::class, 'activity'])->middleware(['auth', 'tenant.access', 'session.unlocked'])->name('profile.activity');
Route::get('/profil/activite/data', [AuthController::class, 'activityData'])->middleware(['auth', 'tenant.access', 'session.unlocked'])->name('profile.activity.data');
Route::get('/session/verrouillee', [AuthController::class, 'lockedScreen'])->middleware(['auth', 'tenant.access'])->name('session.locked');
Route::post('/session/verrouiller', [AuthController::class, 'lockSession'])->middleware(['auth', 'tenant.access'])->name('session.lock');
Route::post('/session/deverrouiller', [AuthController::class, 'unlockSession'])->middleware(['auth', 'tenant.access'])->name('session.unlock');
Route::post('/session/pin-oublie', [AuthController::class, 'unlockWithPassword'])->middleware(['auth', 'tenant.access'])->name('session.forgot-pin');
Route::post('/session/envoi-reinitialisation-pin', [AuthController::class, 'sendPinResetEmail'])->middleware(['auth', 'tenant.access'])->name('session.send-pin-reset');

Route::get('/mot-de-passe-oublie', [AuthController::class, 'showForgotPassword'])->name('password.request');
Route::post('/mot-de-passe-oublie', [AuthController::class, 'sendPasswordResetLink'])->name('password.email');
Route::get('/reinitialiser-mot-de-passe', [AuthController::class, 'showResetPassword'])->name('password.reset');
Route::post('/reinitialiser-mot-de-passe', [AuthController::class, 'updatePassword'])->name('password.update');
Route::get('/reinitialiser-pin', [AuthController::class, 'showResetPin'])->name('pin.reset');
Route::post('/reinitialiser-pin', [AuthController::class, 'updatePin'])->name('pin.reset.update');

Route::get('/boutique', [OnlineStoreController::class, 'index'])->name('storefront.index');
Route::post('/boutique/commandes', [OnlineStoreController::class, 'storeOrder'])->name('storefront.orders.store');

Route::middleware(['auth', 'tenant.access', 'session.unlocked', 'device.selected'])->group(function (): void {
Route::post('/langue/{locale}', [LibraireProController::class, 'switchLocale'])->name('locale.switch');
Route::get('/', [LibraireProController::class, 'dashboard'])->name('dashboard');
Route::get('/guide-fonctionnalites', [LibraireProController::class, 'functionalityGuide'])->name('functionality-guide');

Route::redirect('/items', '/catalogue?panel=articles')->name('legacy.items');
Route::redirect('/items/add', '/catalogue?panel=ajouter')->name('legacy.items.add');
Route::redirect('/services/add', '/catalogue?panel=ajouter-service')->name('legacy.services.add');
Route::redirect('/category/view', '/catalogue?panel=categories')->name('legacy.categories.view');
Route::redirect('/brands/view', '/catalogue?panel=marques')->name('legacy.brands.view');
Route::redirect('/variants/view', '/catalogue?panel=variantes')->name('legacy.variants.view');
Route::redirect('/items/labels', '/catalogue/etiquettes')->name('legacy.items.labels');
Route::redirect('/import/items', '/catalogue?panel=import&kind=items')->name('legacy.import.items');
Route::redirect('/import/services', '/catalogue?panel=import&kind=services')->name('legacy.import.services');
Route::redirect('/pos', '/caisse')->name('legacy.pos');
Route::redirect('/sales/add', '/caisse')->name('legacy.sales.add');
Route::redirect('/sales', '/modules/sales?section=list')->name('legacy.sales');
Route::redirect('/sales_payments', '/modules/sales?section=payments')->name('legacy.sales.payments');
Route::redirect('/sales_payments/', '/modules/sales?section=payments');
Route::redirect('/sales_return', '/modules/sales?section=returns')->name('legacy.sales.returns');
Route::redirect('/delivery', '/modules/sales?section=delivery')->name('legacy.delivery');
Route::redirect('/invoice', '/modules/invoices?section=invoices')->name('legacy.invoice');
Route::redirect('/purchase/add', '/modules/purchases?section=add')->name('legacy.purchase.add');
Route::redirect('/purchase', '/modules/purchases?section=list')->name('legacy.purchase');
Route::redirect('/purchase_return', '/modules/purchases?section=returns')->name('legacy.purchase.returns');
Route::redirect('/expense', '/modules/finance?section=expenses')->name('legacy.expense');
Route::redirect('/expense/add', '/modules/finance?section=expense-add')->name('legacy.expense.add');
Route::redirect('/expense/category', '/modules/finance?section=expense-categories')->name('legacy.expense.categories');
Route::redirect('/quotation/add', '/modules/invoices?section=estimate-add')->name('legacy.quotation.add');
Route::redirect('/quotation', '/modules/invoices?section=estimates')->name('legacy.quotation');
Route::redirect('/customers/add', '/modules/contacts?section=customer-add')->name('legacy.customers.add');
Route::redirect('/customers', '/modules/contacts?section=customers')->name('legacy.customers');
Route::redirect('/import/customers', '/modules/contacts?section=import-customers')->name('legacy.import.customers');
Route::redirect('/suppliers/add', '/modules/contacts?section=supplier-add')->name('legacy.suppliers.add');
Route::redirect('/suppliers', '/modules/contacts?section=suppliers')->name('legacy.suppliers');
Route::redirect('/import/suppliers', '/modules/contacts?section=import-suppliers')->name('legacy.import.suppliers');
Route::redirect('/customers_advance/add', '/modules/finance?section=advance-add')->name('legacy.advance.add');
Route::redirect('/customers_advance', '/modules/finance?section=advances')->name('legacy.advance');
Route::redirect('/customer_coupon/generate', '/modules/finance?section=customer-coupon-add')->name('legacy.customer_coupon.add');
Route::redirect('/customer_coupon', '/modules/finance?section=customer-coupons')->name('legacy.customer_coupon');
Route::redirect('/discount_coupon/add', '/modules/finance?section=coupon-add')->name('legacy.discount_coupon.add');
Route::redirect('/discount_coupon/view', '/modules/finance?section=coupons')->name('legacy.discount_coupon');
Route::redirect('/accounts/add', '/modules/finance?section=account-add')->name('legacy.accounts.add');
Route::redirect('/accounts', '/modules/finance?section=accounts')->name('legacy.accounts');
Route::redirect('/money_transfer', '/modules/finance?section=transfers')->name('legacy.money_transfer');
Route::redirect('/money_deposit', '/modules/finance?section=deposits')->name('legacy.money_deposit');
Route::redirect('/accounts/cash_transactions', '/modules/finance?section=cash')->name('legacy.cash_transactions');
Route::redirect('/stock_adjustment/add', '/stock?panel=stock-adjustment-add')->name('legacy.stock_adjustment.add');
Route::redirect('/stock_adjustment', '/stock?panel=stock-adjustments')->name('legacy.stock_adjustment');
Route::redirect('/stock_transfer/add', '/stock?panel=stock-transfer-add')->name('legacy.stock_transfer.add');
Route::redirect('/stock_transfer/view', '/stock?panel=stock-transfers')->name('legacy.stock_transfer');
Route::redirect('/users/view', '/modules/settings?section=users')->name('legacy.users');
Route::redirect('/roles/view', '/modules/settings?section=roles')->name('legacy.roles');
Route::redirect('/sms', '/modules/settings?section=messaging')->name('legacy.sms');
Route::redirect('/templates/sms', '/modules/settings?section=message-templates')->name('legacy.sms.templates');
Route::redirect('/reports/profit_loss', '/modules/reports?section=profit-loss')->name('legacy.report.profit_loss');
Route::redirect('/reports/sales_and_payments', '/modules/reports?section=sales-payments')->name('legacy.report.sales_payments');
Route::redirect('/reports/customer_orders', '/modules/reports?section=customer-orders')->name('legacy.report.customer_orders');
Route::redirect('/reports/gstr_1', '/modules/reports?section=gstr-1')->name('legacy.report.gstr_1');
Route::redirect('/reports/gstr_2', '/modules/reports?section=gstr-2')->name('legacy.report.gstr_2');
Route::redirect('/reports/sales_gst_report', '/modules/reports?section=sales-gst')->name('legacy.report.sales_gst');
Route::redirect('/reports/purchase_gst_report', '/modules/reports?section=purchase-gst')->name('legacy.report.purchase_gst');
Route::redirect('/reports/sales_tax', '/modules/reports?section=sales-tax')->name('legacy.report.sales_tax');
Route::redirect('/reports/purchase_tax', '/modules/reports?section=purchase-tax')->name('legacy.report.purchase_tax');
Route::redirect('/reports/supplier_items', '/modules/reports?section=supplier-items')->name('legacy.report.supplier_items');
Route::redirect('/reports/sales', '/modules/reports?section=sales')->name('legacy.report.sales');
Route::redirect('/reports/sales_return', '/modules/reports?section=sales-return')->name('legacy.report.sales_return');
Route::redirect('/reports/seller_points', '/modules/reports?section=seller-points')->name('legacy.report.seller_points');
Route::redirect('/reports/purchase', '/modules/reports?section=purchases')->name('legacy.report.purchase');
Route::redirect('/reports/purchase_return', '/modules/reports?section=purchase-return')->name('legacy.report.purchase_return');
Route::redirect('/reports/expense', '/modules/reports?section=expenses')->name('legacy.report.expense');
Route::redirect('/reports/stock', '/modules/reports?section=stock')->name('legacy.report.stock');
Route::redirect('/reports/item_sales', '/modules/reports?section=item-sales')->name('legacy.report.item_sales');
Route::redirect('/reports/return_item', '/modules/reports?section=return-items')->name('legacy.report.return_items');
Route::redirect('/reports/purchase_payments', '/modules/reports?section=purchase-payments')->name('legacy.report.purchase_payments');
Route::redirect('/reports/sales_payments', '/modules/reports?section=sales-payments-list')->name('legacy.report.sales_payments');
Route::redirect('/reports/sales_return_payments', '/modules/reports?section=sales-return-payments')->name('legacy.report.sales_return_payments');
Route::redirect('/reports/stock_transfer', '/modules/reports?section=stock-transfer')->name('legacy.report.stock_transfer');
Route::redirect('/reports/sales_summary', '/modules/reports?section=sales-summary')->name('legacy.report.sales_summary');
Route::redirect('/warehouse', '/modules/settings?section=warehouses')->name('legacy.warehouse');
Route::redirect('/store_profile/update/2', '/modules/settings?section=company')->name('legacy.store_profile');
Route::redirect('/sms/api', '/modules/settings?section=sms-api')->name('legacy.sms_api');
Route::redirect('/tax', '/catalogue?panel=impots')->name('legacy.tax');
Route::redirect('/units', '/catalogue?panel=unites')->name('legacy.units');
Route::redirect('/units/', '/catalogue?panel=unites');
Route::redirect('/payment_types', '/modules/settings?section=payment-types')->name('legacy.payment_types');
Route::redirect('/payment_types/', '/modules/settings?section=payment-types');
Route::redirect('/country', '/modules/settings?section=countries')->name('legacy.country');
Route::redirect('/state', '/modules/settings?section=states')->name('legacy.state');
Route::redirect('/users/password_reset', '/modules/settings?section=password')->name('legacy.password');

Route::get('/catalogue', [LibraireProController::class, 'catalog'])->name('catalog');
Route::get('/stock', [LibraireProController::class, 'stock'])->name('stock');
Route::get('/catalogue/data', [LibraireProController::class, 'catalogData'])->name('catalog.data');
Route::get('/catalogue/recherche-produits', [LibraireProController::class, 'productQuickSearch'])->name('catalog.quick-search');
Route::post('/catalogue/articles', [LibraireProController::class, 'storeItem'])->name('catalog.items.store');
Route::put('/catalogue/articles/{item}', [LibraireProController::class, 'updateItem'])->name('catalog.items.update');
Route::delete('/catalogue/articles/{item}', [LibraireProController::class, 'destroyItem'])->name('catalog.items.destroy');
Route::post('/catalogue/categories', [LibraireProController::class, 'storeCategory'])->name('catalog.categories.store');
Route::put('/catalogue/categories/{category}', [LibraireProController::class, 'updateCategory'])->name('catalog.categories.update');
Route::delete('/catalogue/categories/{category}', [LibraireProController::class, 'destroyCategory'])->name('catalog.categories.destroy');
Route::post('/catalogue/marques', [LibraireProController::class, 'storeBrand'])->name('catalog.brands.store');
Route::put('/catalogue/marques/{brand}', [LibraireProController::class, 'updateBrand'])->name('catalog.brands.update');
Route::delete('/catalogue/marques/{brand}', [LibraireProController::class, 'destroyBrand'])->name('catalog.brands.destroy');
Route::post('/catalogue/unites', [LibraireProController::class, 'storeUnit'])->name('catalog.units.store');
Route::put('/catalogue/unites/{unit}', [LibraireProController::class, 'updateUnit'])->name('catalog.units.update');
Route::delete('/catalogue/unites/{unit}', [LibraireProController::class, 'destroyUnit'])->name('catalog.units.destroy');
Route::post('/catalogue/taxes', [LibraireProController::class, 'storeTax'])->name('catalog.taxes.store');
Route::put('/catalogue/taxes/{tax}', [LibraireProController::class, 'updateTax'])->name('catalog.taxes.update');
Route::delete('/catalogue/taxes/{tax}', [LibraireProController::class, 'destroyTax'])->name('catalog.taxes.destroy');
Route::post('/catalogue/variantes', [LibraireProController::class, 'storeVariant'])->name('catalog.variants.store');
Route::get('/variantes', [VariantController::class, 'index'])->name('variants.index');
Route::get('/variantes/data', [VariantController::class, 'data'])->name('variants.data');
Route::get('/variantes/ajouter', [VariantController::class, 'create'])->name('variants.create');
Route::post('/variantes', [VariantController::class, 'store'])->name('variants.store');
Route::get('/variantes/{variant}', [VariantController::class, 'show'])->name('variants.show');
Route::get('/variantes/{variant}/modifier', [VariantController::class, 'edit'])->name('variants.edit');
Route::put('/variantes/{variant}', [VariantController::class, 'update'])->name('variants.update');
Route::post('/variantes/{variant}/dupliquer', [VariantController::class, 'duplicate'])->name('variants.duplicate');
Route::post('/variantes/{variant}/basculer', [VariantController::class, 'toggle'])->name('variants.toggle');
Route::delete('/variantes/{variant}', [VariantController::class, 'destroy'])->name('variants.destroy');
Route::post('/catalogue/import', [LibraireProController::class, 'importItems'])->name('catalog.import');
Route::get('/catalogue/import/exemple/{kind}', [LibraireProController::class, 'importExample'])->name('catalog.import.example');
Route::post('/catalogue/stock/ajustements', [LibraireProController::class, 'storeStockAdjustment'])->name('catalog.stock-adjustments.store');
Route::post('/catalogue/stock/transferts', [LibraireProController::class, 'storeStockTransfer'])->name('catalog.stock-transfers.store');
Route::post('/catalogue/stock/inventaires', [LibraireProController::class, 'storeStocktake'])->name('catalog.stocktakes.store');
Route::post('/catalogue/stock/inventaires/{stocktake}/comptes', [LibraireProController::class, 'updateStocktake'])->name('catalog.stocktakes.counts.update');
Route::post('/catalogue/stock/inventaires/{stocktake}/terminer', [LibraireProController::class, 'completeStocktake'])->name('catalog.stocktakes.complete');
Route::get('/catalogue/stock/articles', [LibraireProController::class, 'stockItemSearch'])->name('catalog.stock-items.search');
Route::get('/catalogue/export', [LibraireProController::class, 'exportCatalog'])->name('catalog.export');
Route::get('/catalogue/etiquettes', [LibraireProController::class, 'labels'])->name('catalog.labels');
Route::get('/caisse', [LibraireProController::class, 'pos'])->name('pos');
Route::get('/caisse/recherche', [LibraireProController::class, 'posSearch'])->name('pos.search');
Route::get('/caisse/coupons/verifier', [LibraireProController::class, 'previewCoupon'])->name('pos.coupons.preview');
Route::post('/caisse', [LibraireProController::class, 'storePosSale'])->name('pos.store');
Route::post('/caisse/tickets', [LibraireProController::class, 'holdPosTicket'])->name('pos.tickets.store');
Route::delete('/caisse/tickets/{ticket}', [LibraireProController::class, 'destroyPosTicket'])->name('pos.tickets.destroy');
Route::post('/ventes', [LibraireProController::class, 'storeSale'])->name('sales.store');
Route::post('/ventes/paiements', [LibraireProController::class, 'storeSalePayment'])->name('sales.payments.store');
Route::patch('/ventes/{sale}', [LibraireProController::class, 'updateSale'])->name('sales.update');
Route::post('/ventes/{sale}/facture', [LibraireProController::class, 'createSaleInvoice'])->name('sales.invoice.store');
Route::get('/ventes/{sale}/pdf', [LibraireProController::class, 'downloadSalePdf'])->name('sales.pdf');
Route::get('/factures/{invoice}/pdf', [LibraireProController::class, 'downloadInvoicePdf'])->name('sales.invoices.pdf');
Route::post('/documents/factures', [CommercialDocumentController::class, 'storeInvoice'])->name('documents.invoices.store');
Route::put('/documents/factures/{invoice}', [CommercialDocumentController::class, 'updateInvoice'])->name('documents.invoices.update');
Route::post('/documents/factures/{invoice}/envoyer', [CommercialDocumentController::class, 'sendInvoice'])->name('documents.invoices.send');
Route::post('/documents/factures/{invoice}/dupliquer', [CommercialDocumentController::class, 'duplicateInvoice'])->name('documents.invoices.duplicate');
Route::post('/documents/factures/{invoice}/annuler', [CommercialDocumentController::class, 'cancelInvoice'])->name('documents.invoices.cancel');
Route::post('/documents/factures/{invoice}/archiver', [CommercialDocumentController::class, 'archiveInvoice'])->name('documents.invoices.archive');
Route::post('/documents/factures/{invoice}/restaurer', [CommercialDocumentController::class, 'restoreInvoice'])->name('documents.invoices.restore');
Route::post('/documents/factures/{invoice}/paiements', [CommercialDocumentController::class, 'storeInvoicePayment'])->name('documents.invoices.payments.store');
Route::get('/documents/factures/{invoice}/pdf', [CommercialDocumentController::class, 'previewInvoicePdf'])->name('documents.invoices.pdf');
Route::get('/documents/factures/data', [CommercialDocumentController::class, 'invoicesData'])->name('documents.invoices.data');
Route::post('/ventes/{sale}/rembourser', [LibraireProController::class, 'refundSale'])->name('sales.refund');
Route::delete('/ventes/{sale}', [LibraireProController::class, 'destroySale'])->name('sales.destroy');
Route::post('/ventes/livraisons', [LibraireProController::class, 'storeDeliveryOrder'])->name('sales.deliveries.store');
Route::patch('/ventes/livraisons/{delivery}', [LibraireProController::class, 'updateDeliveryOrder'])->name('sales.deliveries.update');
Route::post('/precommandes', [LibraireProController::class, 'storeOnlineOrder'])->name('online-orders.store');
Route::patch('/precommandes/{onlineOrder}', [LibraireProController::class, 'updateOnlineOrderStatus'])->name('online-orders.status.update');
Route::get('/precommandes/{onlineOrder}/encaisser', [LibraireProController::class, 'prepareOnlineOrderSale'])->name('online-orders.sale.prepare');
Route::post('/devis', [LibraireProController::class, 'storeQuotation'])->name('quotations.store');
Route::patch('/devis/{quotation}', [LibraireProController::class, 'updateQuotationStatus'])->name('quotations.update');
Route::post('/devis/{quotation}/convertir', [LibraireProController::class, 'convertQuotationToSale'])->name('quotations.convert');
Route::delete('/devis/{quotation}', [LibraireProController::class, 'destroyQuotation'])->name('quotations.destroy');
Route::post('/documents/devis', [CommercialDocumentController::class, 'storeEstimate'])->name('documents.estimates.store');
Route::put('/documents/devis/{estimate}', [CommercialDocumentController::class, 'updateEstimate'])->name('documents.estimates.update');
Route::post('/documents/devis/{estimate}/transition', [CommercialDocumentController::class, 'transitionEstimate'])->name('documents.estimates.transition');
Route::post('/documents/devis/{estimate}/dupliquer', [CommercialDocumentController::class, 'duplicateEstimate'])->name('documents.estimates.duplicate');
Route::post('/documents/devis/{estimate}/convertir', [CommercialDocumentController::class, 'convertEstimate'])->name('documents.estimates.convert');
Route::get('/documents/devis/{estimate}/pdf', [CommercialDocumentController::class, 'previewEstimatePdf'])->name('documents.estimates.pdf');
Route::get('/achats/data', [LibraireProController::class, 'purchasesData'])->name('purchases.data');
Route::post('/achats', [LibraireProController::class, 'storePurchase'])->name('purchases.store');
Route::post('/achats/{purchase}/recevoir', [LibraireProController::class, 'receivePurchase'])->name('purchases.receive');
Route::post('/achats/paiements', [LibraireProController::class, 'storePurchasePayment'])->name('purchases.payments.store');
Route::get('/achats/{purchase}/pdf', [LibraireProController::class, 'downloadPurchasePdf'])->name('purchases.pdf');
Route::post('/achats/retours', [LibraireProController::class, 'storePurchaseReturn'])->name('purchases.returns.store');
Route::get('/contacts/data', [LibraireProController::class, 'contactsData'])->name('contacts.data');
Route::post('/contacts', [LibraireProController::class, 'storeContact'])->name('contacts.store');
Route::put('/contacts/{contact}', [LibraireProController::class, 'updateContact'])->name('contacts.update');
Route::delete('/contacts/{contact}', [LibraireProController::class, 'destroyContact'])->name('contacts.destroy');
Route::post('/contacts/import', [LibraireProController::class, 'importContacts'])->name('contacts.import');
Route::get('/contacts/import/exemple/{kind}', [LibraireProController::class, 'contactImportExample'])->name('contacts.import.example');
Route::get('/avances/data', [LibraireProController::class, 'customerAdvancesData'])->name('customer-advances.data');
Route::post('/avances', [LibraireProController::class, 'storeCustomerAdvance'])->name('customer-advances.store');
Route::delete('/avances/{advance}', [LibraireProController::class, 'destroyCustomerAdvance'])->name('customer-advances.destroy');
Route::post('/depenses', [LibraireProController::class, 'storeExpense'])->name('expenses.store');
Route::post('/depenses/categories', [LibraireProController::class, 'storeExpenseCategory'])->name('expenses.categories.store');
Route::post('/coupons', [LibraireProController::class, 'storeCoupon'])->name('coupons.store');
Route::put('/coupons/{coupon}', [LibraireProController::class, 'updateCoupon'])->name('coupons.update');
Route::delete('/coupons/{coupon}', [LibraireProController::class, 'destroyCoupon'])->name('coupons.destroy');
Route::post('/remises', [LibraireProController::class, 'storeDiscountRule'])->name('discounts.store');
Route::put('/remises/{discountRule}', [LibraireProController::class, 'updateDiscountRule'])->name('discounts.update');
Route::delete('/remises/{discountRule}', [LibraireProController::class, 'destroyDiscountRule'])->name('discounts.destroy');
Route::post('/comptes', [LibraireProController::class, 'storeFinancialAccount'])->name('accounts.store');
Route::put('/comptes/{account}', [LibraireProController::class, 'updateFinancialAccount'])->name('accounts.update');
Route::delete('/comptes/{account}', [LibraireProController::class, 'destroyFinancialAccount'])->name('accounts.destroy');
Route::post('/comptes/depots', [LibraireProController::class, 'storeMoneyDeposit'])->name('accounts.deposits.store');
Route::post('/comptes/transferts', [LibraireProController::class, 'storeMoneyTransfer'])->name('accounts.transfers.store');
Route::post('/caisse/registre/ouvrir', [LibraireProController::class, 'openCashRegister'])->name('cash-register.open');
Route::post('/caisse/registre/mouvements', [LibraireProController::class, 'storeCashRegisterMovement'])->name('cash-register.movements.store');
Route::post('/caisse/registre/{session}/fermer', [LibraireProController::class, 'closeCashRegister'])->name('cash-register.close');
Route::post('/parametres/theme', [LibraireProController::class, 'updateTheme'])->name('settings.theme.update');
Route::post('/parametres/societe', [LibraireProController::class, 'updateCompanyProfile'])->name('settings.company.update');
Route::post('/parametres/modules', [LibraireProController::class, 'updateModuleSettings'])->name('settings.modules.update');
Route::post('/parametres/caisse', [LibraireProController::class, 'updatePosSettings'])->name('settings.pos.update');
Route::post('/parametres/appareils-virtuels', [LibraireProController::class, 'updateVirtualDeviceSettings'])->name('settings.virtual-devices.update');
Route::post('/parametres/documents-pdf', [LibraireProController::class, 'updateDocumentSettings'])->name('settings.documents.update');
Route::post('/parametres/messagerie', [LibraireProController::class, 'updateMessagingSettings'])->name('settings.messaging.update');
Route::post('/parametres/messagerie/envoyer', [LibraireProController::class, 'sendManualMessage'])->name('settings.messaging.send');
Route::post('/parametres/messagerie/modeles', [LibraireProController::class, 'storeMessageTemplate'])->name('settings.message-templates.store');
Route::put('/parametres/messagerie/modeles/{key}', [LibraireProController::class, 'updateMessageTemplate'])->name('settings.message-templates.update');
Route::delete('/parametres/messagerie/modeles/{key}', [LibraireProController::class, 'destroyMessageTemplate'])->name('settings.message-templates.destroy');
Route::post('/parametres/magasin-courant', [LibraireProController::class, 'updateCurrentStore'])->name('settings.current-store.update');
Route::post('/parametres/magasins', [LibraireProController::class, 'storeStore'])->name('settings.stores.store');
Route::put('/parametres/magasins/{storeKey}', [LibraireProController::class, 'updateStore'])->name('settings.stores.update');
Route::delete('/parametres/magasins/{storeKey}', [LibraireProController::class, 'destroyStore'])->name('settings.stores.destroy');
Route::post('/parametres/types-paiement', [LibraireProController::class, 'storePaymentType'])->name('settings.payment-types.store');
Route::put('/parametres/types-paiement/{key}', [LibraireProController::class, 'updatePaymentType'])->name('settings.payment-types.update');
Route::delete('/parametres/types-paiement/{key}', [LibraireProController::class, 'destroyPaymentType'])->name('settings.payment-types.destroy');
Route::post('/parametres/pays', [LibraireProController::class, 'storeCountry'])->name('settings.countries.store');
Route::put('/parametres/pays/{key}', [LibraireProController::class, 'updateCountry'])->name('settings.countries.update');
Route::delete('/parametres/pays/{key}', [LibraireProController::class, 'destroyCountry'])->name('settings.countries.destroy');
Route::post('/parametres/etats', [LibraireProController::class, 'storeState'])->name('settings.states.store');
Route::put('/parametres/etats/{key}', [LibraireProController::class, 'updateState'])->name('settings.states.update');
Route::delete('/parametres/etats/{key}', [LibraireProController::class, 'destroyState'])->name('settings.states.destroy');
Route::post('/parametres/groupes-fiscaux', [LibraireProController::class, 'storeTaxGroup'])->name('settings.tax-groups.store');
Route::put('/parametres/groupes-fiscaux/{key}', [LibraireProController::class, 'updateTaxGroup'])->name('settings.tax-groups.update');
Route::delete('/parametres/groupes-fiscaux/{key}', [LibraireProController::class, 'destroyTaxGroup'])->name('settings.tax-groups.destroy');
Route::put('/parametres/mot-de-passe', [LibraireProController::class, 'updateAccountPassword'])->middleware('auth')->name('settings.password.update');
Route::post('/parametres/utilisateurs', [LibraireProController::class, 'storeUser'])->name('settings.users.store');
Route::put('/parametres/utilisateurs/{user}', [LibraireProController::class, 'updateUser'])->name('settings.users.update');
Route::put('/parametres/utilisateurs/{user}/pin', [LibraireProController::class, 'updateUserPin'])->name('settings.users.pin');
Route::delete('/parametres/utilisateurs/{user}', [LibraireProController::class, 'destroyUser'])->name('settings.users.destroy');
Route::post('/parametres/roles', [LibraireProController::class, 'storeRole'])->name('settings.roles.store');
Route::put('/parametres/roles/{role}', [LibraireProController::class, 'updateRole'])->name('settings.roles.update');
Route::delete('/parametres/roles/{role}', [LibraireProController::class, 'destroyRole'])->name('settings.roles.destroy');
Route::get('/modules/{module}', [LibraireProController::class, 'module'])->name('module');

// Virtual devices: selection & heartbeat (no device.selected middleware)
Route::get('/appareil/selectionner', [VirtualDeviceController::class, 'selectDevice'])->name('device.select');
Route::post('/appareil/connecter', [VirtualDeviceController::class, 'connectDevice'])->name('device.connect');
Route::post('/appareil/deconnecter', [VirtualDeviceController::class, 'disconnectDevice'])->name('device.disconnect');
Route::post('/appareil/heartbeat', [VirtualDeviceController::class, 'heartbeat'])->name('device.heartbeat');

// Virtual devices: management (owner only)
Route::get('/appareils', [VirtualDeviceController::class, 'index'])->name('devices.index');
Route::post('/appareils', [VirtualDeviceController::class, 'store'])->name('devices.store');
Route::put('/appareils/{device}', [VirtualDeviceController::class, 'update'])->name('devices.update');
Route::put('/appareils/{device}/statut', [VirtualDeviceController::class, 'toggleStatus'])->name('devices.toggle');
Route::delete('/appareils/{device}', [VirtualDeviceController::class, 'destroy'])->name('devices.destroy');
});
